README.adoc
"your" = belonging to you, "you're" = contraction meaning "you are"
=> Fix grammatical error in README

ykman/driver_otp.py
Add workaround for bug in NEO, where the device will blink when it's not supposed to. Also improve logging a bit.
=> Improve slot based OATH with touch

README.adoc
=> Update installation info in README

debian/changelog
To agree with version in `__init__.py`.
=> Set Debian version to 0.6.0~dev

test/on_yubikey/test_misc.py, test/on_yubikey/test_oath.py, test/on_yubikey/test_openpgp.py, test/on_yubikey/test_piv.py, test/on_yubikey/test_slot.py, test/on_yubikey/util.py
See commit log for a high-level description of the changes.
=> Tidy up tests some more

ykman/cli/__main__.py
=> always set up logger before importing other modules

docker/xenial/Dockerfile
Make maximal use of cached layers to speed up (non-Travis) build times.
=> Optimize Dockerfile

test/test_util.py, ykman/cli/info.py, ykman/device.py, ykman/util.py
- read form factor info if available and save on device
- print out form factor in ykman info.
=> add support for form factor tag

ykman/cli/info.py, ykman/util.py
- Drop unused NFC bit
- Update FIDO2 bit
=> Update capabilities a bit

test/on_yubikey/test_cli_slot.py, ykman/cli/__main__.py, ykman/cli/otp.py
- rename slot command to otp
- rename otp command to yubiotp
=> Rename slot command to otp

test/test_device.py, ykman/cli/__main__.py, ykman/cli/info.py, ykman/cli/mode.py, ykman/descriptor.py, ykman/device.py, ykman/driver.py, ykman/driver_ccid.py, ykman/driver_otp.py, ykman/driver_u2f.py, ykman/opgp.py, ykman/util.py
Ping @dagheyman 
NOT READY TO BE MERGED!
=> [WIP] Read and parse new device config

test/test_util.py, ykman/cli/otp.py, ykman/driver_otp.py, ykman/otp.py, ykman/util.py
Move out OTP functionality into a controller class.
=> OTP controller

test/on_yubikey/test_cli_otp.py, ykman/cli/otp.py, ykman/otp.py
This will be needed for FIPS support.
=> Add ability to set OTP access code in ykman otp settings

ykman/cli/otp.py
Potential solution to review comment https://github.com/Yubico/yubikey-manager/pull/123#discussion_r197691547
=> Extract function explain_fips_status

test/on_yubikey/test_cli_misc.py, test/on_yubikey/test_cli_oath.py, ykman/cli/info.py, ykman/cli/oath.py, ykman/oath.py
This would merge into #123.
Does the output format look reasonable?
=> Add overall FIPS status to ykman info

ykman/cli/config.py
- clarify format in help text
- add flag to generate random lock code
=> configuration lock code improvements

ykman/cli/config.py, ykman/cli/fido.py, ykman/cli/otp.py
- Prompt if lock code is set and `--lock-code` is not given
- Fail if `--force` is given, lock code is set and `--lock-code` is not given
- Fail if `--lock-code` is given and lock code is not set
=> Improve application lock code UX

.travis.yml, appveyor.yml, ykman.spec
Use PyInstaller to build ykman as a single executable on macOS and Windows.
=> Build stand alone executable

ykman/cli/fido.py, ykman/cli/oath.py, ykman/cli/opgp.py, ykman/cli/piv.py, ykman/driver_ccid.py, ykman/fido.py, ykman/oath.py, ykman/opgp.py, ykman/piv/__init__.py, ykman/piv/errors.py, ykman/piv/sw_util.py
=> Merge SW enums

test/on_yubikey/test_piv.py, ykman/cli/piv.py, ykman/util.py
builds on https://github.com/Yubico/yubikey-manager/pull/189
=> piv: support parsing multiple pem certs

ykman/util.py
=> Enum members must not be accessed with 'self'

ykman/cli/piv.py
- In the CLI, add length validation on the PIN and PUK
- Clarify help texts a bit
Should fix #210
=> piv: make sure pin/puk is 6 - 8 chars

.travis.yml, MANIFEST.in
- create the source release in travis
- include manpage in source package
=> travis: do a src release

ykman/cli/oath.py
password was always being asked in prompt
=> oath: fix sending password as cli arg

ykman/cli/otp.py
=> Fix otp example in help

ykman/cli/otp.py, ykman/otp.py
Merges #240 and introduces an object for slot configuration.
=> Refactor otp config

test/on_yubikey/cli_piv/test_key_management.py, ykman/cli/config.py, ykman/cli/oath.py, ykman/cli/opgp.py, ykman/cli/otp.py, ykman/cli/piv.py, ykman/cli/util.py, ykman/opgp.py, ykman/piv.py
This replaces most uses of `UpperCaseChoice` and post-processing with uses of the new types `EnumNameChoice` and `EnumValueChoice`.
=> Extract utility classes for choices of enum members

ykman/descriptor.py
This reverts commit 1e8b16ca644c382f912051f144253e2e7bf83bc5.
On OpenBSD at least, this causes a use-after-free in libusb, rendering the entire tool useless. This ends up calling `libusb_init`, which sets up a lot of global context. I'm guessing that that's the root cause, but I'm honestly not sure.
=> Prevent use-after-free when querying usb devices

ykman/cli/piv.py
Handles this: https://github.com/pyca/cryptography/issues/4949
=> piv: handle validity set to year 0

test/on_yubikey/framework/__init__.py, test/on_yubikey/test_opgp.py
See https://github.com/Yubico/yubikey-manager/pull/260#issuecomment-522442749
=> Fix unit tests crashing in py2

ykman/cli/__main__.py
=> Catch error when pcscd is not running

ykman/descriptor.py, ykman/util.py
=> Ignore YubiHSM when enumerating USB devices

ykman/cli/opgp.py
=> opgp: document set-touch command better

ykman/cli/oath.py
before:
```
$ ykman -l DEBUG oath add kaka MZXW6===
[ .. ]
2020-02-03T14:12:16+0000 DEBUG [ykman.device.__init__:198] Read config from device...
2020-02-03T14:12:16+0000 DEBUG [ykman.driver_ccid.send_apdu:228] SEND: 00a4040008a000000527471117
2020-02-03T14:12:16+0000 DEBUG [ykman.driver_ccid.send_apdu:230] RECV: 5669727475616c206d6772202d2046572076657273696f6e20342e332e379000
2020-02-03T14:12:16+0000 DEBUG [ykman.driver_ccid.send_apdu:228] SEND: 001d000000
2020-02-03T14:12:16+0000 DEBUG [ykman.driver_ccid.send_apdu:230] RECV: 0c0101ff02040074d4c003013f9000
2020-02-03T14:12:16+0000 DEBUG [ykman.device.__init__:200] Success!
2020-02-03T14:12:16+0000 DEBUG [ykman.driver_ccid.send_apdu:228] SEND: 00a4040007a0000005272001
2020-02-03T14:12:16+0000 DEBUG [ykman.driver_ccid.send_apdu:230] RECV: …
```
=> Avoid one unnecessary credential query list when adding a new cred

test/on_yubikey/test_cli_oath.py
- Reset YubiKey after test suite
- Test that OATH application can store 32 creds
=> Improve OATH integration tests a bit

ykman/scancodes/__init__.py, ykman/scancodes/it.py
Ported over from https://github.com/Yubico/yubikey-personalization-gui/commit/02f1aa520ee3b33377a5f1e206d769792594e6ed
=> static pw: add support for IT keyboard layout

.github/workflows/codeql-analysis.yml
https://github.blog/2020-09-30-code-scanning-is-now-available/
=> actions: add codeql-action

ykman/cli/opgp.py
Signed version of https://github.com/Yubico/yubikey-manager/pull/362
=> Fix typo in `ykman openpgp set-touch` help message

ykman/scancodes/__init__.py, ykman/scancodes/uk.py
Add support for UK keyboard layout
resolve #376
=> static password: add UK keyboard layout

doc/development.adoc
hey there, big fan of the company, tools, and software :)
looks like there's no longer a `setup.py` so it seems the dev documentation about `pip install -e .` is bit rotted. i added some basic instructions for the new `poetry` based setup for those looking to hack on the project, like me - if there's a better way that y'all have moved on to, that'd be great as well!
thanks for your time and efforts on this project!
=> add poetry-based dev instrucions

ykman/pcsc/__init__.py
=> Use shutil.which to find pkill

ykman/cli/otp.py, yubikit/core/otp.py
Fixes #453.
This PR does two things (one per commit):
1. Fix a regression in commit bb5ba2d. (Thanks @fschlich!)
2. Display the Modhex alphabet in the error message.
=> Fix illegal modhex message

doc/Development.adoc
=> Add build instructions on RPM-based distributions.

ykman/cli/openpgp.py, ykman/openpgp.py
This adds CLI commands for changing the Reset Code, as well as for resetting the PIN (using either Reset Code or Admin PIN).
=> OpenPGP: Add commands for changing and using Reset Code.

ykman/_cli/openpgp.py
I already found that one fixed in other places, this one was missing.
=> Fix grammar typo
