ykman/cli/oath.py

> ykman oath code -H
File "/Users/dchang/Build/yubikey-manager/ykman/cli/oath.py", line 327, in code
creds.sort()
AttributeError: 'generator' object has no attribute 'sort'
We try to run `creds.sort()` - however, if the `show hidden -h` flag is on,
then we never change the generator into a list, causing an error.
Change `creds` into a list immediately.
I would have preferred `creds = list(controller.calculate_all())`.
However, using list comprehension rather than the list constructor is
used when we list all credentials, hence matching the style of other
code.
(It's worth noting that because we called a function `list` and thus
overrode the list constructor, running `list()` on any generator was
going to fail.)
We could have also used `sorted()` instead of `creds.sort()`. However,
the …

Fix bug where we try to sort a generator

---

test/test_cli_commands_on_yubikey.py
ykman/cli/util.py

Some services (e.g. Dropbox, Google) will have spaces in the base32
code. They do it because base32 does not contain spaces and it makes it
easier for a human to read and type.
In the case of ykman, it's likely that folks copy and paste the code and
thus will also copy over the spaces. As it is safe to ignore the spaces,
we should.

Strip out spaces from OATH base32 code entry

---

README.adoc

Added ` brew install ykman` as the main installation method.
Also changed to use _Python 2_  as the default instructions for installing from source since that is (still) the default on macOS.

Updated macOS Install instructions

---

ykman/cli/opgp.py
ykman/opgp.py

CLI: Print remaining PIN retries in `$ ykman openpgp info` command
API: make `get_remaining_pin_tries()` a public method.

OpenPGP: print remaining PIN retries in info cmd

---

test/test_cli_commands_on_yubikey.py
ykman/cli/slot.py

Providing the public id, private id and secret key from the interactive prompt was broken.

Fixes for programming OTPs in the prompt

---

ykman/cli/__main__.py
ykman/cli/mode.py
ykman/cli/oath.py
ykman/cli/piv.py
ykman/cli/slot.py
ykman/descriptor.py
ykman/driver_ccid.py
ykman/driver_otp.py
ykman/driver_u2f.py
ykman/piv.py

I went through all `except` statements and added error logging where it seemed appropriate. My basic rules of thumb for when this was not needed were:
- If the `except` block (or the code following a `pass` statement) attempts to recover from the error
- In `except` block branches that raise new errors
- If the `except` block is on the CLI level and appropriate feedback is already given

Log lightly handled errors

---

ykman/oath.py

Newer devices don't allow keys shorter than 14 bytes.

Zero-pad short OATH HMAC keys

---

test/test_cli_commands_on_yubikey.py
ykman/cli/piv.py
ykman/piv.py

So we don't have to expose `_get_puk_tries()` and spend retries on querying when the retry count needs to be displayed in yubikey-manager-qt, for example.

Return number of retries on PIV PUK change failure

---

doc/development.adoc
test/test_cli_commands_on_yubikey.py
test/test_external_libs.py
test/util.py
ykman/cli/__main__.py
ykman/device.py
ykman/driver.py
ykman/driver_ccid.py
ykman/driver_otp.py

The integration tests now reliably pass in both Linux and Mac!

Clean up tests

---

test/on_yubikey/util.py

This lets unittest report that the tet was skipped because the
environment variables were not set, instead of falsely "detecting" that
required modes are incorrect.

Fix message about skipping tests when serial env var is not set

---

test/on_yubikey/test_piv.py
test/test_piv.py
ykman/cli/piv.py
ykman/piv.py

This way it'll be less weird to reuse it in other non-CLI code.

PIV: Move random mgmt key generation from module cli.piv to piv

---

NEWS
test/on_yubikey/test_cli_piv.py
test/on_yubikey/test_piv.py
ykman/piv.py

`PivController.verify()` now calls itself again if it also called `authenticate()` to unlock a protected management key. This means that a following `sign()` call with PIN policy ALWAYS will no longer require an additional preceding `verify()` call, whereas the `authenticate()` call would previously consume the "verifiedness" required by the ALWAYS policy.

Fix PIV cert generation when sign requires PIN

---

test/on_yubikey/test_piv.py
test/util.py

- Remove unused type conversions that didn't work in Python 2
- Pass `u''` strings to make `x509.NameAttribute` happy in Python 2
- Don't use `assertRaisesRegex` which was added in Python 3

Fix destructive tests in Python 2

---

ykman/piv.py

Fixes `CryptographyDeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.` from cryptography.
See https://github.com/pyca/cryptography/issues/3659

piv: use verify instead of verifier

---

test/on_yubikey/test_interfaces.py
ykman/driver_otp.py

Using the OTP interface directly after using FIDO might result in a timeout. If this happens, wait 3 seconds and try again.
To reproduce the error that this fixes:
```
from ykman import driver_fido, driver_otp
next(driver_fido.open_devices()).read_config()
next(driver_otp.open_devices()).read_config()
```

otp: try reading config twice if timeout

---

ykman/cli/fido.py

This code path instead fails if the reset window has closed, so don't print the message in this case.

Don't print re-insert prompt if --force is given to fido reset

---

ykman/cli/fido.py

The new code should be logically equivalent to the old code.

Flatten PIN prompt control flow in fido set-pin

---

ykman/cli/fido.py

- Allow empty current pin in internal change_pin function. The FIPS U2F PIN has only one command to both set and change PIN, and there's no good way to tell if a PIN is already set, so this is needed for initially setting the U2F PIN.
- Extract controller-polymorphic try_reset function in fido reset command

Refactorisations in preparation of adding FIPS support

---

test/on_yubikey/test_cli_otp.py
ykman/cli/otp.py
ykman/otp.py

Some YubiKey firmware versions silently fail to change the access code, as @dagheyman [discovered][report] in #122. ~~With these changes , ykman will make a couple of extra calls to the YubiKey to verify that the access code was in fact set or deleted as expected. If not, an error is raised. See the inline docstring and comments for details on how these deductions are made.~~ With these changes, ykman will refuse to perform these operations on affected firmware versions.
[report]: https://github.com/Yubico/yubikey-manager/pull/122#issuecomment-399855281

Refuse set/delete access code on firmware versions 4.3.2 - 4.3.5

---

ykman/cli/otp.py

gc link variable: no longer used as of 6c55124a; fixes travis build

fix travis build

---

ykman/cli/fido.py

We did not handle `fido reset` with multiple keys connected well, it required all keys to be removed. Supporting doing reset on a specific YubiKey might be possible, but requires bigger changes. Let's start with explicitly blocking this and giving a proper error message when multiple keys are connected.

fido: block reset when multiple keys are connected

---

ykman/device.py

not doing this might break the touch to eject feature

config: always set the ccid bit for usb

---

test/test_scancodes.py
ykman/scancodes/us.py

"`" should be supported when using the US keyboard layout. See:
https://github.com/Yubico/yubikey-personalization-gui/blob/master/lib/us-scanedit.cpp#L131

static pw: add support for ` in us keyboard layout

---

test/on_yubikey/test_cli_oath.py
ykman/cli/oath.py

See #160 
For Python 2 compatibility.

oath: use explicit unicode string when needed

---

ykman/cli/config.py
ykman/cli/fido.py
ykman/cli/oath.py
ykman/cli/opgp.py
ykman/cli/otp.py
ykman/cli/piv.py

By showing all interactive prompts on stderr instead, we make commands like this possible: 
`$ ykman piv generate-key 9a - > out.txt` (which would otherwise redirect the prompt to `out.txt`.) Follows [POSIX standard](https://unix.stackexchange.com/a/381081) better as well.

prompt on stderr on all prompts

---

ykman/cli/__main__.py
ykman/device.py
ykman/driver_ccid.py

Add minimal support for external smart card readers with a `-r/--reader` flag to ykman. Works only for CCID commands and for a single YubiKey.
Example usage with a HID OmniKey Reader:
`$ ykman --reader HID oath code`

Add support for external reader flag

---

ykman/piv.py

An alternative approach would be to add similar methods to APDUError instead.

Add class methods for inspecting verify fail (0x63cX) status words

---

test/on_yubikey/util.py
test/test_piv.py
test/util.py
ykman/cli/piv.py
ykman/device.py
ykman/piv.py

This allows us to tailor the GUI optimally for each kind of YubiKey (i.e., not show options for unsupported algorithms).

Extract method PivController.supported_algorithms

---

ykman/cli/config.py
ykman/cli/fido.py
ykman/cli/mode.py
ykman/cli/oath.py
ykman/cli/opgp.py
ykman/cli/otp.py
ykman/cli/piv.py

Since e1031c79f311b67b509e735ecf1cb04c84c41d94, all input prompts are written to standard error instead of standard out, but we forgot to do the same for confirmation prompts.

Print also confirmation prompts to stderr

---

ykman/piv.py

This is an equivalent change to the one that merged in yubico-piv-tool in https://github.com/Yubico/yubico-piv-tool/pull/178.
Tested on yubikey neo.
Correctly decodes as ```[9999-9999-999999-0-1-0000000000300001]``` on this [online decoder site](http://www.christhilges.com/fasc-n/index.php).

Fix FASC-N encoding

---

test/on_yubikey/cli_piv/test_misc.py
ykman/cli/piv.py
ykman/piv.py

Add commands for writing and reading arbitrary PIV objects. The read commands should prompt for the pin if needed the write command should prompt for pin or management key if needed.
requested in #183

piv: add read-object and write-object commands

---

ykman/cli/opgp.py
ykman/opgp.py

Suggested changes:
- Print touch policies in info command (as requested in #203)
- Rename enum names to be more human friendly, as they are printed to the user
- Don't give a success message (most other ykman commands stay silent on success)
- Make the touch command set-only (use info for getting current status)
- Give meaningful names to the metavars (printed in the help)

opengp touch changes

---

ykman/cli/util.py

On Python3 dict.items() returns a view object and changing dictionary
values while iterating this view may lead to unexpected results when we
resolve the context like an attempt to resolve the same object twice.
This patch fixes this by creating a copy of the underlying dict in the
resolve() method.

Fix how the context is resolved

---

ykman/cli/__main__.py
ykman/driver_ccid.py

- add `-r/--reader` flag to ykman list, for listing available smart card readers (both yubikeys and external)
- relax the filtering, so that it's possible to select reader with any substring of the reader name. For example `OMNI` would now work on a `HID Global OMNIKEY 5022 Smart Card Reader` reader, before `HID` was required.

add support fort listing smart card readers

---

test/on_yubikey/test_cli_config.py
ykman/cli/config.py
ykman/cli/util.py

A small hack to accept `openpgp` as an option for the `ykman config` commands, without renaming the enum. Initially tried with a callback, but the type is handled before that in click.

config: accept opengp as OPGP

---

ykman/cli/piv.py

- print the serial number of the certificate in `piv info`
- cryptography 2.5 added support for reading full DN strings from certificates, try to use that in `piv info` if available. Fall back to old behavior if its not. 
- clarify in help-texts that the `--subject` option is for the subject common name

piv: improve piv info command

---

ykman/cli/piv.py

- fixes #230 (the bug mentioned in the thread, not specifying the version)
- also print the algo name correctly

Fix fallback logic in piv info for cryptogtaphy versions < 2.5

---

setup.py
ykman/cli/otp.py
ykman/otp.py

This adds some integration with upload.yubico.com to the ykman CLI.
- If the `--upload` option is given to the `ykman otp yubiotp` command, the CLI will initiate a key upload and then open the prepared form in the user's browser.
- The key and private ID are sent in the POST body of a background HTTP request, and the server responds with a request ID that is then opened as a GET URL in the browser.
- If the POST request fails, nothing is written to the YubiKey.
- The POST request includes a `User-Agent` header identifying the ykman version.
- The key is not written to disk or exposed to browser history.
- The POST request is sent and processed in the library so the same logic can be reused in the GUI.
This code currently writes quite a lot of output in the CLI, perhaps we'll want to focus …

Add `--upload` feature to `otp yubiotp` command

---

ykman/device.py
ykman/driver_ccid.py

- When probing capabilities on the NEO, the FIDO U2F applet is selected, which fails with access denied on latest Windows 10 (if not run as administrator). Leads to failures like this https://github.com/Yubico/yubioath-desktop/issues/368
- Catch error, log it.
- If the device is a NEO and version is over 3.3.0 report U2F as a supported capability.

Support NEO on newer Windows versions

---

ykman/cli/__main__.py
ykman/descriptor.py

- Add a `name` property on the descriptor object (uses PID and version to come up with a name)
- Simplify SKY specific code in list command
- If any device failed to open, list it based on the information available in the descriptor
Examples with FIDO only device on Win 10:
```
$ ykman.exe list
Security Key NFC [FIDO]
$ ykman.exe info
Error: Failed connecting to Security Key NFC [FIDO]
```

ykman list: list based on descriptors

---

ykman/cli/otp.py
ykman/otp.py

Add support for `USE_NUMERIC_KEYPAD` flag to better support HOTP credentials in combination with AZERTY keyboard layouts. 
To enable:
`$ ykman otp settings SLOT --use-numeric-keypad`

settings: add support for USE_NUMERIC_KEYPAD

---

test/on_yubikey/cli_piv/test_key_management.py
test/on_yubikey/test_cli_misc.py

- Fix an incorrect invocation of `ykman info --check-fips` (one string `'info --check-fips'` instead of two (`'info'`, `'--check-fips'`)
- Update tests of `ykman piv import-certificate` to reflect that verification of certificate/key pairing is now opt-in instead of opt-out

Fix broken tests

---

test/on_yubikey/cli_piv/test_generate_cert_and_csr.py
test/on_yubikey/cli_piv/test_key_management.py
test/on_yubikey/test_cli_config.py
test/on_yubikey/test_cli_oath.py
test/on_yubikey/test_cli_openpgp.py
test/on_yubikey/test_fips_u2f_commands.py
test/on_yubikey/test_piv.py
test/test_external_libs.py

- `TestExternalLibraries` does not need a YubiKey
- Some tests attempted RSA key generation on ROCA vulnerable devices
- OATH and/or OpenPGP tests sometimes crashed for no apparent reason, seems to be related to `test_mode_command` running just before them.

Fix some broken tests

---

ykman/native/pyusb.py

On macOS, sometimes `usb.core.find(True, idVendor=0x1050, beckend=get_usb_backend)` (called in `ykman.desctiptor._gen_descriptors`) returned an incorrect list of devices, where a device that had been removed was still present. This change fixes that.

usb: load backend every time

---

ykman/native/util.py

This fixes an [LGTM alert](https://lgtm.com/projects/g/Yubico/yubikey-manager/snapshot/f73dda2b16d50f5186b8fa4ed4ee90d5ce7d3743/files/ykman/native/util.py#x12957e531cc49dee:1).

Remove unneeded re-export of load_library

---

setup.py

`yubikey-manager` depends on APIs introduced in `fido2` v0.7.0.
If `fido2` follows semantic versioning conventions, this ought to be `fido2 ~= 0.7.0`.
I ran into this issue while packaging `ykman` v3.0.0.

setup.py: Correct dependency on fido2

---

NEWS
ykman/cli/opgp.py

- Clarify "touch policy not supported" message to say the policy is not supported by the user's particular YubiKey
- Fail faster if `ykman openpgp set-touch att ...` when YubiKey does not support attestation
- Prompt for admin PIN only after the checks are done

Improve user feedback in opgp set-touch

---

NEWS
ykman/otp.py

Before:
```
$ ykman otp yubiotp 1 -SgG --upload
Using YubiKey serial as public ID: vvccccjffvkj
Using a randomly generated private ID: 36c941002411
Using a randomly generated secret key: bd86a981ae88490310d064dd6a0328b1
Traceback (most recent call last):
File "/home/emlun/dev/yubikey-manager/.python-venv/bin/ykman", line 11, in <module>
load_entry_point('yubikey-manager', 'console_scripts', 'ykman')()
File "/home/emlun/dev/yubikey-manager/ykman/cli/__main__.py", line 268, in main
cli(obj={})
File "/home/emlun/dev/yubikey-manager/.python-venv/lib/python3.8/site-packages/click/core.py", line 764, in __call__
return self.main(*args, **kwargs)
File "/home/emlun/dev/yubikey-manager/.python-venv/lib/python3.8/site-packages/click/core.py", line 717, in main
rv = self.invoke(ctx)
File …
```

Fix crash when YubiOTP upload fails

---

test/on_yubikey/framework/__init__.py
test/on_yubikey/test_opgp.py

This fixes 2 issues:
```
$ DESTRUCTIVE_TEST_YUBIKEY_SERIALS=7800014 python setup.py test
running test
running egg_info
writing yubikey_manager.egg-info/PKG-INFO
writing dependency_links to yubikey_manager.egg-info/dependency_links.txt
writing entry points to yubikey_manager.egg-info/entry_points.txt
writing requirements to yubikey_manager.egg-info/requires.txt
writing top-level names to yubikey_manager.egg-info/top_level.txt
reading manifest file 'yubikey_manager.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'ChangeLog'
warning: no files found matching 'resources/*'
warning: manifest_maker: MANIFEST.in, line 10: 'recursive-exclude' expects <dir> <pattern1> <pattern2> ...
writing manifest file 'yubikey_manager.egg-info/SOURCES.txt'
running …
```

Fix integration tests

---

ykman/cli/__main__.py

If flow passes the `ctx.exit()` on line 222, it will always reach this log statement, even if no devices did in fact fail.

Make fallback log message in list_keys more correct

---

.github/workflows/macOS.yml
ykman/cli/util.py

Currently, `ykman openpgp set-touch` fails when using the option `cached-fixed`. This is a fix for that.
```
$ ykman openpgp set-touch SIG CACHED-FIXED
Usage: ykman openpgp set-touch [OPTIONS] KEY POLICY
Try "ykman openpgp set-touch -h" for help.
Error: Invalid value for "POLICY": invalid choice: CACHED_FIXED. (choose from OFF, ON, FIXED, CACHED, CACHED-FIXED)
```

util: support enums with dash in UpperCaseChoice

---

ykman/cli/__main__.py

Several OS permission restrictions typically makes ykman fail to open the device, causing a error message. Try to hint at the reason in the message, even if we can't be sure.
This should be triggered by:
- Running a FIDO command on recent Windows 10 without administrator privileges.
- Running a OTP command on macOS Catalina, without making the application to allow "Input Monitoring" in the System Settings. The OS typically prompts for this, at least once.
- Possibly other cases (maybe missing udev on Linux? Not tested.)
Related: https://github.com/Yubico/yubikey-manager-qt/pull/223

cli: hint at permissions when open device fails

---

test/on_yubikey/cli_piv/test_misc.py

```
test_write_read_object (test.on_yubikey.cli_piv.test_misc.additional_tests.<locals>.Misc_5.0.3_1234567) ... /home/emlun/dev/yubikey-manager/test/on_yubikey/cli_piv/test_misc.py:28:
DeprecationWarning: Please use assertEqual instead.
self.assertEquals('test data\n', output)
ok
```

Fix test warning about wrong assert function

---

setup.py
ykman/cli/__main__.py
ykman/descriptor.py

Solves the issue when Smart Card Service on Windows is disabled and ykman qt could not open at all.
Also fixed a typo.

Better error handling when failing to open CCID context

---

.github/workflows/build.yml
.github/workflows/macOS.yml
.github/workflows/source-package.yml
.github/workflows/windows.yml
.gitignore
doc/development.adoc
setup.py
test/on_yubikey/framework/__init__.py
test_requirements.txt
tox.ini

`python setup.py test` is deprecated, see
https://setuptools.readthedocs.io/en/latest/history.html#v41-5-0:
>#1878: Formally deprecated the test command, with the recommendation
that users migrate to tox.

Migrate to tox

---

test/on_yubikey/framework/__init__.py
ykman/native/pyusb.py

- Retry `ykman_cli` and `open_device` calls in tests
Tests routinely fail randomly with spurious errors like "card was reset" and "I/O error". This helps recover from some of those.
- Cache pyusb backend to avoid segfault issues in libusb destructors
See commit message on be5ec2fc for in-depth description.

Improve test stability

---

ykman/cli/oath.py

Found this by accident, but it prints the multiple hits error when there is no hits.

oath: code -s gave wrong error message

---

ykman/scancodes/__init__.py
ykman/scancodes/bepo.py

Port of https://github.com/Yubico/yubikey-personalization-gui/commit/e23ee929e67f13e704818cb0a3ce622231d2027e
With this change, there is no longer any keyboard layout for static passwords in yubikey-personalization-gui not also available in ykman CLI (FYI @klali ). We should direct users that wish to add more layouts to this project.

static password: add BEPO keyboard layout

---

ykman/cli/__main__.py

This behavior was changed in https://github.com/Yubico/yubikey-manager/commit/c838a4d6f2a9350a6c1feb2956695d1a3c103f37 , possibly by mistake.

list: try all transports

---

.github/workflows/build.yml
.pre-commit-config.yaml

- Use non-deprecated flake8 hook
- Make sure the same checks are done on CI and locally by running pre-commit in GitHub Actions

pre-commit cleanups

---

ykman/opgp.py

Resolves #279.
I've tested this on a YubiKey 5 Nano and NFC running firmware version 5.2.4, but more testing from others would be appreciated; in particular, I haven't actually verified that it still works when KDF is disabled, or on older firmware versions that don't support KDF at all...

opgp: add support for KDF PINs

---

ykman/cli/fido.py

This fixes two issues in `ykman fido delete`:
- .lower() was called on the query but not on the username or rp id
- there was no way to fully qualify a username + rp id, in the way they are presented by `ykman fido list`

fido: fix delete command query qualifiers

---

ykman/driver_ccid.py

Without this fix, CCID connections would typically be closed twice, once by the destructor and once by the caller. I don't think this affects much, but it's incorrect and makes the debug log more confusing.
driver_otp.py have a similar check.
See the log below for an example:
```
$ ykman --log-level DEBUG oath info
2020-05-27T08:22:44+0200 INFO [ykman.logging_setup.setup:59] Initialized logging for ykman version: 3.1.1
2020-05-27T08:22:44+0200 DEBUG [ykman.descriptor.Descriptor.open_device:88] transports: 0x4, self.mode.transports: 0x6
2020-05-27T08:22:44+0200 DEBUG [ykman.descriptor.open_device:93] Opening driver for serial: None, type: YUBIKEY.YK4, mode: FIDO+CCID
2020-05-27T08:22:44+0200 DEBUG [ykman.descriptor.open_device:95] Attempt 1 of 10
2020-05-27T08:22:44+0200 DEBUG …
```

ccid: prevent closing same connection twice

---

ykman/device.py

Let's only use the response from the GET CAPABILITIES command on YubiKeys with firmware version 5 or higher, since YubiKey 4 in some cases seem to report incorrectly. 
Testing:
- Make sure the `ykman info` command works correctly for a few devices in different modes.

device: fix check for new capabilities

---

ykman/opgp.py

All `openpgp` commands that requires verification currently fails on a YubiKey NEO, because the attempt to read the KDF data. See below. This fix handles the error response.
Introduced in #325 , so the bug is not in any released version yet.
```
Set PIN retry counters to: 10 10 10? [y/N]: y
2020-05-27T13:30:58+0200 DEBUG [ykman.driver_ccid.send_apdu:228] SEND: b'00ca00f900'
2020-05-27T13:30:58+0200 DEBUG [ykman.driver_ccid.send_apdu:230] RECV: b'6a83'
2020-05-27T13:30:58+0200 DEBUG [ykman.driver_ccid.send_apdu:228] SEND: b'00ca00c400'
2020-05-27T13:30:58+0200 DEBUG [ykman.driver_ccid.send_apdu:230] RECV: b'007f7f7f0303039000'
2020-05-27T13:30:58+0200 DEBUG [ykman.driver_ccid.close:270] Close <ykman.driver_ccid.CCIDDriver object at 0x106d23150>
2020-05-27T13:30:58+0200 ERROR …
```

opgp: handle failed KDF attempt on NEO

---

.bandit
.github/workflows/build.yml
.pre-commit-config.yaml
doc/development.adoc
ykman/cli/util.py
ykman/driver_ccid.py
ykman/oath.py
ykman/opgp.py
ykman/otp.py
ykman/piv.py
ykman/util.py

This adds [Bandit](https://github.com/PyCQA/bandit) integration as a pre-commit hook, which also runs on GitHub actions.
It also either fixes or suppresses some of the warnings:
- Add logging to empty Exception blocks
- Suppress warnings for use of SHA1 in a HMAC contexts
- Suppress warning for use of ECB in relation to the PIV management key
- Drop one use of assert, convert one use of assert to a regular check
- Suppress warning for use of subprocess module, HTTPSConnection, the word "secret" in some constants
To run bandit manually:
`$ bandit -r .`
Note that exclude directories are defined in the `.bandit` config file as well as in the pre-commit config.
I opted for suppressing warnings directly in the code with the `# nosec` syntax, since we already do that for flake8 exceptions and …

add Bandit security scanner and suppress some of the warnings

---

ykman/cli/otp.py

Currently, for the "otp chalresp" command, the tool allows the user to specify
both generate and TOTP, but it ignores the generate and prompts the user for a
key, anyhow.
This change checks generate by itself and generates the key if it's true. If
TOTP is chosen, it outputs the generated key as Base32, since that's what it
prompts the user for if generate isn't chosen.
If generate and TOTP are not meant to be used together, then instead of this
change, we should print an error message if both are chosen.

Generate key if generate is chosen with TOTP

---

README.adoc

by merging this request we would be able to:
- share the information on how to install YubiKey Manager on FreeBSD;
- take care of the decision made on https://github.com/Yubico/yubikey-manager/pull/139 by @dagheyman
- inform that Yubico do **NOT** maintain any official package for this platform;
- offer the easy option to install YubiKey Manager via `pkg`;
- document and link the option to use the ports tree, but refer the official FreeBSD Handbook.

Add FreeBSD install documentation

---

ykman/cli/otp.py
ykman/cli/util.py
ykman/otp.py

When I used `ykman` I was confused about programming two yubikeys with
the same key in hmac-sha1: I didn't know if the key was read as a string
or in hex. I'm clarifying the description to explain that the key may be
either hex or base32. See also issue #482.

Improve description of cli chalresp KEY argument.

---

tests/device/cli/test_hsmauth.py
tests/device/test_hsmauth.py
tests/test_hsmauth.py
ykman/_cli/__main__.py
ykman/_cli/hsmauth.py
ykman/hsmauth.py
yubikit/hsmauth.py

This adds support for the YubiHSM Auth application, available on YubiKeys with FW 5.4.3.

Add YubiHSM Auth application

---

.github/dependabot.yml

This PR introduces the following change:
* Add a Dependabot configuration to update GitHub action versions via PRs.
There are several actions that are no longer current (`actions/checkout@v3` is now at v4 for example, and `actions/upload-artifact@v1` is now at v3). Rather than submit a PR to update these just once, the new Dependabot config will make sure they stay up-to-date on a regular basis.

Add a Dependabot config to update GitHub action versions

---

tests/device/cli/piv/test_fips.py
tests/device/cli/piv/test_pin_puk.py
ykman/_cli/piv.py
ykman/piv.py

Ignore it on newer devices with metadata support, and make sure to clear the flag on set-retries.

PIV: Improve handling of legacy "PUK blocked" flag

---

ykman/pcsc/__init__.py

`yubikey-agent` is an SSH agent written in Go that uses the PIV module of a YubiKey for SSH[1].
Since it takes a persistent transaction on the YubiKey, using e.g. `ykman` will fail when it's active. I think it's tedious to always send a SIGHUP to it whenever I want to use `ykman`, so I added this small patch that does that for me. Inspired by what `age-plugin-yubikey` is also doing[2].
Not sure about Windows support, but I left it out because `yubikey-agent` doesn't do any Windows AFAIK and SIGHUP isn't supported there.
[1] https://github.com/FiloSottile/yubikey-agent
[2] https://github.com/str4d/age-plugin-yubikey/commit/1913838f8ed4b30c756c3c20ea5fdf1680ea97ca

Send SIGHUP to `yubikey-agent` if it's running and the connection fails

---

generate-man.py
man/ykman.1
ykman/_cli/openpgp.py

This PR fixes man page generation, and adds more explicit wording around the behavior of the OpenPGP attestation key, as it relates to factory reset and touch policies.

Improve --help text and man page generation
